name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt install -y build-essential libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev

      - name: Linting
        run: cargo clippy

  create-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create vendor
        run: cargo vendor

      - name: Set configuration
        run: |
          mkdir .cargo && touch .cargo/.config
          mv build-aux/cargo_offline_config .cargo/config

      - name: Create package
        run: |
         touch flatpak.tar
         tar --exclude=flatpak.tar -czvf flatpak.tar .

      - uses: actions/upload-artifact@v2
        with:
          name: flatpak_build
          path: flatpak.tar
